sudo: false
language: ruby
cache: bundler
script: "TESTOPTS=-v bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.5
  - 2.3.1
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  include:
    - rvm: 2.1
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
