sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - 2.4
  - jruby-19mode
  - jruby-head
  - rbx
  - rbx-19mode
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx
    - rvm: rbx-19mode
